var NumberOfWords = 100

var words = new BuildArray(NumberOfWords)

// Use the following variables to
// define your random words:
words[1] = "to be beaten up by a kangaroo?"
words[2] = "to post a selfie, even during an earthquake?"
words[3] = "to become an animal hoarder?"
words[4] = "to become a stripper?"
words[5] = "to sell feet pics?"
words[6] = "to have a sugar daddy?"
words[7] = "to have an Only Fans page?"
words[8] = "to get detained for harassing a police officer?"
words[9] = "to get arrested?"
words[10] = "to have been the first to kiss a person?"
words[11] = "to get robbed?"
words[12] = "to buy a sex robot in the year 2040?"
words[13] = "the best flirt?"
words[14] = "to spend most money?"
words[15] = "to have children first?"
words[16] = "to get married first?"
words[17] = "to be a successful radio host?"
words[18] = "to be a successful influencer?"
words[19] = "to be drunk at work?"
words[20] = "to give birth to the antichrist?"
words[21] = "to get away with murder?"
words[22] = "not to take a shower for a week?"
words[23] = "to gossip?"
words[24] = "to survive alone on an island?"
words[25] = "to die first in Hunger Games"
words[26] = "to embarrass a friend in public?"
words[27] = "to have a threesome?"
words[28] = "to have the highest body count?"
words[29] = "to date two people at the same time?"
words[30] = "to watch porn as soon as they wake up?"
words[31] = "to be on Paradise Hotel?"
words[32] = "to be on Ex On The Beach?"
words[33] = "to throw up tonight?"
words[34] = "to spend all their money on something stupid?"
words[35] = "to marry a drug lord?"
words[36] = "to get punched in the face?"
words[37] = "to forget people’s names?"
words[38] = "to get the whole gang in trouble?"
words[39] = "to win at beer pong?"
words[40] = "to get pregnant while on birth control?"
words[41] = "to go on a blind date arranged by their mom"
words[42] = "to go off on their own on a night out"
words[43] = "to fall asleep on the bus and pass their station?"
words[44] = "to fall off the stairs while holding a cake?"
words[45] = "to eat a bug?"
words[46] = "to eat a toenail?"
words[47] = "to eat something alive?"
words[48] = "to eavesdrop on a conversation?"
words[49] = "to fake their death?"
words[50] = "to become a gold digger?"
words[51] = "to become a motivational speaker?"
words[52] = "to become an internet troll?"
words[53] = "to become famous for something stupid?"
words[54] = "to stay up late arguing with internet trolls?"
words[55] = "to stay up late sexting with random strangers on the internet?"
words[56] = "to marry a foreigner for a Green Card?"
words[57] = "to marry a millionaire?"
words[58] = "to marry a stranger in Las Vegas?"
words[59] = "to Kiss & Tell?"
words[60] = "to have a crush on a co-worker?"
words[61] = "to have a disease named after them?"
words[62] = "to have the most cliché tattoo?"
words[63] = "to have their nudes leaked?"
words[64] = "to open a yoga studio?"
words[65] = "to snatch someone’s partner?"
words[66] = "to help a thief escape?"
words[67] = "to remain calm during a storm?"
words[68] = "to forget to pick the kids from school?"
words[69] = "to be two hours late to their own event?"
words[70] = "to accidentally set the house on fire?"
words[71] = "to make up a false story?"
words[72] = "to stalk a crush?"
words[73] = "to be caught telling a lie?"
words[74] = "to help a friend bury a body?"
words[75] = "to smoke next to a no-smoking sign?"
words[76] = "to catch feelings after a one night stand?"
words[77] = "to catfish someone on the internet?"
words[78] = "to be tired of their partner after two weeks?"
words[79] = "to wander off on their own on a night out?"
words[80] = "to become a sex addict?"
words[81] = "to catch an STD?"
words[82] = "to buy a weird sex toy and use it on somebody?"
words[83] = "to drunkenly kiss a friend on lips they've never dated?"
words[84] = "to try cannibalism?"
words[85] = "to not remember this night tomorrow?"
words[86] = "to flirt to get a free drink?"
words[87] = "to get plastic surgery?"
words[88] = "to survive a zombie apocalypse?"
words[89] = "to be an alien undercover?"
words[90] = "to be an FBI agent undercover?"
words[91] = "to go on a killing spree after a bad day?"
words[92] = "to offend millions of people all over Facebook?"
words[93] = "to start their own weird religion?"
words[94] = "to get into a fight over road rage?"
words[95] = "to build a sex dungeon?"
words[96] = "to accidentally kill someone?"
words[97] = "to climb (and die) on Mount Everest?"
words[98] = "to get kicked out and banned from an orgy?"
words[99] = "to become a sugar daddy / sugar momma?"
words[100] = "to get into a fight with a Disney costumed character?"

function BuildArray(size){
    this.length = size
    for (var i = 1; i <= size; i++){
        this[i] = null}
    return this
}

function PickRandomWord(frm) {
// Generate a random number between 1 and NumberOfWords
    var rnd = Math.ceil(Math.random() * NumberOfWords)

// Display the word inside the text box
    frm.WordBox.value = words[rnd]
}